### ISSUE TITLE
what is a scale parameter?

### ISSUE THREAD

**Issue by erex** [dill/RDistanceBook#15]
in "simpledf" plain folk won't know what a scale parameter is; it is tautological to say a scale function has its name because it affects the scale.

might use terms like "compress" and "elongate" to get across the idea of what effect changing the scale has

**Comment by dill** [comment]
This is a very good point! I've gone with "stretch" and "squash" in 3a19267

I was trying to avoid using the word "shape" for fear of confusion later when talking about hazard-rate and clearly forgot about immediate confusion...
